spring:
    profiles:
      active: dev



spring:
  application:
    name: cloudconfig-dev
  profiles: dev




spring:
  application:
    name: cloudconfig-test
  profiles: test



spring:
  application:
    name: cloudconfig-pro
  profiles: pro