spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: cloudconfig-dev1199zzzzzz



---
spring:
  profiles: test
  application:
    name: cloudconfig-test


---
spring:
  profiles: pro
  application:
    name: cloudconfig-pro
