spring:
  profiles:
    active: dev
---
spring:
  application:
    name: cloud-client-provider-dev
  profiles: dev
server:
  port: 10001
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://node1:9000/eureka/
    instance:
      prefer-ip-address: true
---
spring:
  application:
    name: cloud-client-provider-dev
  profiles: dev
server:
  port: 10001
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://node1:9000/eureka/
    instance:
      prefer-ip-address: true