spring:
  profiles:
    active: dev
---
spring:
  application:
    name: cloud-client-provider-dev
  profiles: dev

server:
  port: 10001
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://node1:9000/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}:${project.version}

---
spring:
  application:
    name: cloud-client-provider-test
  profiles: test

server:
  port: 10001
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://node1:9000/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}:${project.version}

